global_frame: map
robot_base_frame: base
update_frequency: 6.0
publish_frequency: 3.0

#set if you want the voxel map published
#publish_voxel_map: false

#set to true if you want to initialize the costmap from a static map
static_map: false

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
width: 7.0
height: 7.0
resolution: 0.05
track_unknown_space: true
unknown_cost_value: -1
#end - COMMENT these lines if you set static_map to true

#START VOXEL STUFF
#map_type: voxel
#origin_z: 0.0
#z_resolution: 0.2
#z_voxels: 10
#unknown_threshold: 10
#mark_threshold: 0
#END VOXEL STUFF
transform_tolerance: 1.0
obstacle_range: 4.0
max_obstacle_height: 2.0
raytrace_range: 6.0
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
#robot_radius: 0.46
footprint_padding: 0.01
inflation_radius: 0.25
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
observation_sources: base_scan
base_scan: {data_type: LaserScan, topic: scan, sensor_frame: velodyne, expected_update_rate: 0.4,
  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
