TrajectoryPlannerROS:
  max_vel_x: 1.25
  min_vel_x: 0.1
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 3.0
  acc_lim_y: 3.0

  yaw_goal_tolerance: 3.0
  xy_goal_tolerance: 0.5

  holonomic_robot: true
