global_frame: map
robot_base_frame: base
update_frequency: 5.0
publish_frequency: 2.5
static_map: true
#rolling_window: true
publish_voxel_map: true
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.3, -0.3], [0.3, -0.3], [0.3, 0.3], [-0.3, 0.3]]
inflation_radius: 0.55
#observation_sources: base_scan
#base_scan: {data_type: LaserScan, topic: scan, sensor_frame: velodyne, expected_update_rate: 0.4,
  #observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
#observation_sources: laser_scan_sensor 
#laser_scan_sensor: {sensor_frame: velodyne, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: velodyne, data_type: PointCloud2, topic: lidar_points, marking: true, clearing: true}
