base_global_planner: global_palnner/GlobalPlanner
planner_frequency:          0     # Global plan updates on new goal or path blocked only
controller_frequency:       20
planner_patience:           5.0
controller_patience:        3.0
conservative_reset_dist:    2.0
recovery_behavior_enabled:  true
clearing_rotation_allowed:  true
shutdown_costmaps:          false
oscillation_timeout:        0.0
oscillation_distance:       0.5
robot_base_frame: base
global_frame: map

