local_costmap:
  global_frame: map_en
  robot_base_frame: base
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  track_unknown_space: true
  unknown_cost_value: -1
